apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        imagePullPolicy: IfNotPresent
        name: hello-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: DB_ADDRESS
            valueFrom:
               configMapKeyRef:
                 name:  {{ .Release.Name }}
                 key: DB_ADDRESS
          - name: DB_USER
            valueFrom:
               secretKeyRef:
                 name:  {{ .Release.Name }}
                 key: DB_USER

        volumeMounts:
        - name: {{ .Release.Name }}-file
          mountPath: /config/config1.yml
          subPath: config1.yml
      volumes:
      - name: {{ .Release.Name }}-file
        configMap:
          name: {{ .Release.Name }}-file
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
